# Generated by Django 3.2.5 on 2021-07-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_contato_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='usuario_agenda',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
